--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DustinMcNeese/OuTSideR-Levels
build-by-default: true
branches:
- main
projects: []
  OuTSideR-Levels: 
    Path: OuTSideR-Levels/
...
